### ISSUE TITLE
Some questions about the Version of DataComp1B used by Recap-DataComp1B

### ISSUE THREAD

**Issue by XavierHeart** [UCSC-VLAA/Recap-DataComp-1B#14]
Hello, this is a good job. I've noticed that the org_caption in the Recap-Datacomp1B dataset is a little different from the original Datacomp1B Text, but the meaning is similar. For example, for https://d2xkh9za9v22a1.cloudfront.net/1551975881_17272285_ADMIN_UPLOAD-list.jpg, the original text describes it as "Piggly Wiggly_CLR® Mold & Mildew Stain Remover_coupon_44993" but in Recap-Datacomp dataset org_caption is: "Shurfine_CLR\xc2\xae Mold & Mildew Stain Remover_coupon_44993" There are many other cases, so I don't have an example here. I'm wondering if Recap-Datacomp1B uses a different version of Datacomp1B or if the raw data is further processed.

Also, for Recap-Datacomp1B the url in the dataset is different from the original url, but points to the same image. This is what puzzles me, for example for this image: https://cf-img.autorevo.com/2004-porsche-911-flowery-branch-ga-6697751/476x476/2330022-6-revo.jpg?1576091095, https://cf-img.autorevo.com/2004-porsche-911-flowery-branch-ga-6697751/476x476/2330022-6-revo.jpg?1576092120, which are from recap and raw respectively datacomp1B of the same item, corresponding to the same sha256 index.

**Comment by xhl-video** [comment]
Hi,  Thanks for your patience. I think the first question may caused by the different decoding methods. The version of our dataset is the same as [this](https://huggingface.co/datasets/mlfoundations/datacomp_1b).  Second, the same sha256 can only ensure the same image according to the img2dataset tool.  So, it may happen the URLs are different but pointing to the same image. Btw, I found there are around 0.29 billion repeated sha256 and I have updated the cleaned one in [huggingface](https://huggingface.co/datasets/UCSC-VLAA/Recap-DataComp-1B/viewer/default/train). Please take a look to see if the new version solves your problems. Thanks.

**Comment by XavierHeart** [comment]
Hi, Thank you for your detailed update and addressing my concerns！
